IntegrationServicesHub/IntegrationServicesHub/Controllers/ContentAgreementsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;
using IntegrationServicesHub.Models.HubModels;
using IntegrationServicesHub.RavenDBConfig;

namespace IntegrationServicesHub.Controllers
{
    public class ContentAgreementsController : Controller
    {
        private static RavenDbCommunication ravenDbCommunication { get; set; }

        public ContentAgreementsController()
        {
             ravenDbCommunication = new RavenDbCommunication("ContentAgreementsDB");
        }

        public ActionResult Index()
        {
            var session = ravenDbCommunication.DocumentStore.OpenSession();
            var result = session.Query<ContentAgreement>().ToList();
            return View(result);
        }

        // GET: ContentAgreements/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: ContentAgreements/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ContentAgreements/Create
        [HttpPost]
        public ActionResult Create(ContentAgreement ca)
        {
            try
            {
                var session = ravenDbCommunication.DocumentStore.OpenSession();
                session.Store(ca);
                session.SaveChanges();
                Thread.Sleep(1500);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: ContentAgreements/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: ContentAgreements/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }


        public ActionResult Delete(UInt64 id)
        {
            try
            {
                var session = ravenDbCommunication.DocumentStore.OpenSession();
                var v = session.Query<ContentAgreement>().Where(r => r.ID == id).FirstOrDefault();
                session.Delete(v);
                session.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

IntegrationServicesHub/IntegrationServicesHub/Controllers/ContentsRightsOwnerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;
using IntegrationServicesHub.Models.HubModels;
using IntegrationServicesHub.RavenDBConfig;

namespace IntegrationServicesHub.Controllers
{
    public class ContentsRightsOwnerController : Controller
    {
        private static RavenDbCommunication ravenDbCommunication { get; set; }

        public ContentsRightsOwnerController()
        {
             ravenDbCommunication = new RavenDbCommunication("ContentRightOwnersDB");
        }

        public ActionResult Index()
        {
            var session = ravenDbCommunication.DocumentStore.OpenSession();
            var result = session.Query<ContentRightsOwner>().ToList();
            return View(result);
        }

        // GET: ContentsRightsOwner/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: ContentsRightsOwner/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ContentsRightsOwner/Create
        [HttpPost]
        public ActionResult Create(ContentRightsOwner cro)
        {
            try
            {
                var session = ravenDbCommunication.DocumentStore.OpenSession();
                session.Store(cro);
                session.SaveChanges();
                Thread.Sleep(1500);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: ContentsRightsOwner/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: ContentsRightsOwner/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

      
        public ActionResult Delete(UInt64 id)
        {
            try
            {
                var session = ravenDbCommunication.DocumentStore.OpenSession();
                var v = session.Query<ContentRightsOwner>().Where(r => r.ID == id).FirstOrDefault();
                session.Delete(v);
                session.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

IntegrationServicesHub/IntegrationServicesHub/Controllers/ServiceProvidersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;
using IntegrationServicesHub.Models.HubModels;
using IntegrationServicesHub.Models.Util.ValueObjects;
using IntegrationServicesHub.RavenDBConfig;

namespace IntegrationServicesHub.Controllers
{
    public class ServiceProvidersController : Controller
    {
        private static RavenDbCommunication ravenDbCommunication { get; set; }

        public ServiceProvidersController()
        {
             ravenDbCommunication = new RavenDbCommunication("ServiceConfigurationDB");
        }

        // GET: ServiceProviders
        public ActionResult Index()
        {
            var session = ravenDbCommunication.DocumentStore.OpenSession();
            var result = session.Query<ServiceProvidersModel>().ToList();
            return View(result);
        }

        // GET: ServiceProviders/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: ServiceProviders/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ServiceProviders/Create
        [HttpPost]
        public ActionResult Create(ServiceProvidersModel serviceProvidersModel)
        {
            try
            {
                var session = ravenDbCommunication.DocumentStore.OpenSession();
                session.Store(serviceProvidersModel);
                session.SaveChanges();
                Thread.Sleep(1500);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: ServiceProviders/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: ServiceProviders/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Delete(UInt64 id)
        {
            try
            {
                var session = ravenDbCommunication.DocumentStore.OpenSession();
                var v = session.Query<ServiceProvidersModel>().Where(r => r.ID == id).FirstOrDefault();
                session.Delete(v);
                session.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

IntegrationServicesHub/IntegrationServicesHub/Views/ServiceProviders/Create.cshtml
@using System
@using System.Activities.Expressions
@using System.Collections.Generic
@using System.Web.UI.WebControls
@model IntegrationServicesHub.Models.HubModels.ServiceProvidersModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
 
   <input type="hidden" name="CreatedDate" value="@DateTime.Now"/>
    <div class="form-horizontal">
        <h4>ServiceProvidersModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        
        <div class="form-group">
            @Html.LabelFor(model => model.ID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ID, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ServiceProviderName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ServiceProviderName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ServiceProviderName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ServiceName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ServiceName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ServiceName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ObjectId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ObjectId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ObjectId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EncryptedName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EncryptedName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EncryptedName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PublishState, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.PublishState, new SelectList(new List<string>{"Not Specified", "Created", "Published"}), new { htmlAttributes = new { @class = "form-control" }})
                @Html.ValidationMessageFor(model => model.PublishState, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ConnectTimeOut, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ConnectTimeOut, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ConnectTimeOut, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ConnectTimeOutBlockTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ConnectTimeOutBlockTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ConnectTimeOutBlockTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Isblocked, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Isblocked)
                    @Html.ValidationMessageFor(model => model.Isblocked, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreatedBy, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreatedBy, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreatedBy, "", new { @class = "text-danger" })
            </div>
        </div>

       
        

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

IntegrationServicesHub/IntegrationServicesHub/Views/ServiceProviders/Index.cshtml
@model System.Collections.Generic.IEnumerable<IntegrationServicesHub.Models.HubModels.ServiceProvidersModel>

@{
    ViewBag.Title = "Service Providers";
}

<ul class="nav navbar-nav">
    <li>@Html.ActionLink("Service Providers List", "Index", "ServiceProviders")</li>
    <li>@Html.ActionLink("Content Agreements List", "Index", "ContentAgreements")</li>
    <li>@Html.ActionLink("Content Rights Owners List", "Index", "ContentsRightsOwner")</li>
    <li>@Html.ActionLink("Multiple Content Services List", "Index", "Home")</li>
    <li>@Html.ActionLink("Multiple Service Prices List", "Index", "Home")</li>
    <li>@Html.ActionLink("Create New", "Create")</li>
</ul>

    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ServiceProviderName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ServiceName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ObjectId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EncryptedName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PublishState)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreatedBy)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreatedDate)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ServiceProviderName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ServiceName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ObjectId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EncryptedName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PublishState)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreatedBy)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreatedDate)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                    @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.ID })
                </td>
            </tr>
        }

    </table>