IntegrationServicesHub/IntegrationServicesHub/Controllers/ContentServiceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;
using IntegrationServicesHub.Models.Util.ValueObjects;
using IntegrationServicesHub.RavenDBConfig;
using Raven.Client.Document;

namespace IntegrationServicesHub.Controllers
{
    public class ContentServiceController : Controller
    {
        public ActionResult Index()
        {
            var ravenDbCommunication = new RavenDbCommunication("ContentServiceDB");
            var session = ravenDbCommunication.DocumentStore.OpenSession();
            var result = session.Query<ContentData>().ToList();
            return View(result);
        }

        public ActionResult CreateNewContent()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreateNewContent(ContentData cd)
        {
            var ravenDbCommunication = new RavenDbCommunication("ContentServiceDB");
            var session = ravenDbCommunication.DocumentStore.OpenSession();
            session.Store(cd);
            session.SaveChanges();
            Thread.Sleep(1500);
            return RedirectToAction("Index");
        }

        public ActionResult Delete(UInt64 id)
        {
            var ravenDbCommunication = new RavenDbCommunication("ContentServiceDB");
            var session = ravenDbCommunication.DocumentStore.OpenSession();
            var v = session.Query<ContentData>().Where(r=>r.ID==id).FirstOrDefault();
            session.Delete(v);
            session.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

IntegrationServicesHub/IntegrationServicesHub/Controllers/ServiceProvidersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;
using IntegrationServicesHub.Models.HubModels;
using IntegrationServicesHub.Models.Util.ValueObjects;
using IntegrationServicesHub.RavenDBConfig;

namespace IntegrationServicesHub.Controllers
{
    public class ServiceProvidersController : Controller
    {
        private static RavenDbCommunication ravenDbCommunication { get; set; }

        public ServiceProvidersController()
        {
             ravenDbCommunication = new RavenDbCommunication("ServiceConfigurationDB");
        }

        // GET: ServiceProviders
        public ActionResult Index()
        {
            var session = ravenDbCommunication.DocumentStore.OpenSession();
            var result = session.Query<ServiceProvidersModel>().ToList();
            return View(result);
        }

        // GET: ServiceProviders/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: ServiceProviders/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ServiceProviders/Create
        [HttpPost]
        public ActionResult Create(ServiceProvidersModel serviceProvidersModel)
        {
            try
            {
                var session = ravenDbCommunication.DocumentStore.OpenSession();
                session.Store(serviceProvidersModel);
                session.SaveChanges();
                Thread.Sleep(1500);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: ServiceProviders/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: ServiceProviders/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Delete(UInt64 id)
        {
            try
            {
                var session = ravenDbCommunication.DocumentStore.OpenSession();
                var v = session.Query<ServiceProvidersModel>().Where(r => r.ID == id).FirstOrDefault();
                session.Delete(v);
                session.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

IntegrationServicesHub/IntegrationServicesHub/Views/Shared/_Layout.cshtml
@using System
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Content Service", "Index", "ContentService")</li>
                    <li>@Html.ActionLink("Service Configurations", "Index", "ServiceProviders")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer class ="nav navbar-nav">
            <p>&copy; MPS Broadband AB</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>